members/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView
from members.models import Member

urlpatterns = patterns('members.views',
	url(r'^$',
		ListView.as_view(
			queryset=Member.objects.order_by('user__first_name', 'user__last_name'),
			context_object_name='member_list',
			template_name='members/members_list.html')),
	url(r'^(?P<slug>\w+)/$',
		DetailView.as_view(
			model=Member,
			slug_field = 'user__username',
			template_name='members/member_page.html')),
)

tsar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'tsar.views.home', name='home'),
	url(r'^$', 'tsar.views.my_page', name='home'),
	url(r'^news/$', 'tsar.views.news', name='news'),

	url(r'^hopur/', include('groups.urls')),
	url(r'^felagi/', include('members.urls')),
	url(r'^vidburdur/', include('events.urls')),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
	url(r'^utskra/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/'}),
	url(r'^checkin/', include('checkin.urls')),
	url(r'^checkin/$', include('checkin.urls')),

	#urls for password reset
	url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
	url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
	url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

from django.conf import settings

if settings.DEBUG:
	urlpatterns += patterns('',
		#(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/martin/devel/tsar/static/' }),
	)

events/models.py
# -*- coding: utf-8 -*-
from django.db import models
from groups.models import Group
from members.models import Member, Position
from django.db.models import get_model
import datetime
from django import forms
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import SplitDateTimeWidget
from markupfield.fields import MarkupField
#from paintstore.fields import ColorPickerField
from colorful.fields import RGBColorField

class Role(models.Model):
	# Roles for participants in an event. (e.g. driver, organiser, instructor,
	# etc.).

	title = models.CharField(max_length=64)

	def __unicode__(self):
		return self.title

class EventType(models.Model):
	# Events may be of several different types that one may like to distinguish
	# between (e.g. exercise, course, meeting, social, etc.).
	#
	# TagTypes also have EventTypes as an exercise may have different tags to a
	# meeting.

	title = models.CharField(max_length=64)
	description = models.TextField(blank=True)
	#color = ColorPickerField(default="#ffffff")
	color = RGBColorField()

	def __unicode__(self):
		return self.title

class TagType(models.Model):
	# TagTypes group tags by type such as organiser, task, conditions, equipment
	# etc.
	#
	# A TagType is associated with one or more EventTypes to which it applies.
	# Most event types will have an organiser but different event types will have
	# different tasks.

	title = models.CharField(max_length=64)
	event_type = models.ManyToManyField(EventType)

	def __unicode__(self):
		return self.title + ": " + ", ".join([et.title for et in self.event_type.all()])

class Tag(models.Model):
	# Events have Tags for analysis. These should be chosen depending on which
	# elements should be focused on in each type of event. Exercises could for
	# example be tagged with first-aid, avalanche rescue or similar techniques.
	#
	# Tags are grouped into TagTypes (e.g. organiser, task, conditions, equipment,
	# etc.).
	title = models.CharField(max_length=64)
	tag_type = models.ForeignKey(TagType)

	def __unicode__(self):
		return self.title
		  
class Event(models.Model):
	# The fundamental object. Most of the magic happens in EventRole, however.
	#
	# An event may have several roles and members can be invited to one or more
	# roles, either as members, or through groups which they belong to.
	#
	# Events come in various types, have locations and can be tagged with
	# techniques employed or something similar that will aid in analysing events.

	title = models.CharField(max_length=64)
	#description = models.TextField(blank=True)
	#description = MarkupField(blank=True,default_markup_type='markdown')
	description = MarkupField(markup_type='markdown')
	#description = MarkupField(blank=True, markup_type='markdown')
	date_time_begin = models.DateTimeField()
	date_time_end = models.DateTimeField()
	event_type = models.ForeignKey(EventType)
	tags = models.ManyToManyField(Tag, through='EventTag', related_name='tag_events', blank=True)

	def invited_roles(self, member):
		# Returns a list of roles a member is invited to.

		invitedroles = []
		#print self.eventrole_set.all()
		for eventrole in self.eventrole_set.all():
			if eventrole.is_open:
				invitedroles.append(eventrole)
			for position in eventrole.invited_positions.all():
				if member in position.member_set.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			for group in eventrole.invited_groups.all():
				if member in group.members.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			if member in eventrole.invited_members.all() and eventrole not in invitedroles:
				invitedroles.append(eventrole)
		return invitedroles

	def responded_roles(self, member):
		# Returns a list of roles a member has responded to.

		respondedroles = []
		for eventrole in self.eventrole_set.all():
			if member in eventrole.responses.all():
				respondedroles.append(eventrole)
		return respondedroles

	#def event_roles (self):
	#	eventroles = []
	#	for eventrole self.eventrole_set.all().
	#		eventroles.append(eventrole)
	#	return eventroles

	# TODO: Need to implement locations. Character fields or just store this all in a GPX file?
	# TODO: Add equipment to log equipment use. Better to add this as a relation rather than a tag?

	def __unicode__(self):
		return self.title

class EventTag(models.Model):
	event = models.ForeignKey(Event)
	tag = models.ForeignKey(Tag)

	def __unicode__(self):
		return self.event.title +' <-> '+ self.tag.title

class EventRole(models.Model):
	# An event may have several roles, and the same group or member may be
	# invited to each of these. So for each role on each event we need an
	# “event role” to which we'll hang the invitations.
	#
	# These EventRoles are associated with:
	# * an event
	# * a role
	# * (optionally) one or more groups through GroupInvitation
	# * (optionally) one or more members through MemberInvitation
	# * (optionally) one or more positions through PositionInvitation
	# * a boolean field indicating whether the event is open to all members
	# * (optionally) one or more members through their responses to the event
	# EventRoles furthermore have:
	# * an optional maximum number of members allowed
	# * an optional minimum number of members required
	# * a boolean indicating whether the role details should be hidden to non-invited members

	event = models.ForeignKey(Event)
	role = models.ForeignKey(Role)
	invited_groups = models.ManyToManyField(Group, through='GroupInvitation', blank=True)
	invited_members = models.ManyToManyField(Member, through='MemberInvitation', related_name='eventrole_invitations', blank=True)
	invited_positions = models.ManyToManyField(Position, through='PositionInvitation', blank=True)
	is_open = models.BooleanField(default=False)
	responses = models.ManyToManyField(Member, through='MemberResponse', related_name='eventrole_responses', blank=True)
	minimum = models.SmallIntegerField(default=0)
	maximum = models.SmallIntegerField(default=0)
	is_hidden = models.BooleanField(default=False)

	def invited(self, member):
		# Returns boolean depending on whether the member is invited to the event.
		# TODO: Unused?

		for position in self.invited_positions.all():
			if member in position.members.all():
				return True
		for group in self.invited_groups.all():
			if member in group.members.all():
				return True
		if member in self.invited_members.all():
			return True
		return False

	def response(self, member):
		# Returns the member's response to the event, unless there is none in
		# which case the response is the string 'U'.

		try:
			mr = MemberResponse.objects.get(event_role=self,member=member)
			#print 'XXX',mr.response
			return mr.response
		except:
			#print 'XXX NO RESPONSE'
			return 'U'

	def __unicode__(self):
		return self.event.title +' '+ self.role.title

class PositionInvitation(models.Model):
	# An intermediary model between an event role and a position.

	event_role = models.ForeignKey(EventRole)
	position = models.ForeignKey(Position)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.position.title

class GroupInvitation(models.Model):
	# An intermediary model between an event role and a group.

	event_role = models.ForeignKey(EventRole)
	group = models.ForeignKey(Group)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.group.title

class MemberInvitation(models.Model):
	# An intermediary model between an event role and a member.

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberResponse(models.Model):
	# An intermediary model between an event role and a member.
	#
	# The MemberResponse details the response (whether the member is attending or
	# will be absent) and the time of the response (important for roles which
	# have a maximum number of slots).

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_RESPONSES = (
		(u'Y',u'Attending'),
		(u'N',u'Absent'),
		(u'U',u'Unclear'),
	)
	response = models.CharField(max_length=1, choices=EVENT_RESPONSES)
	# TODO: Should we add this to help gather a bit of data on member event response behaviour or is it a bit to Big-Brothery?
	#prior = models.CharField(max_length=1, choices=EVENT_RESPONSES, blank=True)
	time_responded = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberAttendance(models.Model):
	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_ATTENDANCE = (
		(u'Y',u'Attended'),
		(u'N',u'Absent'),
	)
	attendance = models.CharField(max_length=1, choices=EVENT_ATTENDANCE)
	time_checkin = models.DateTimeField(blank=True, null=True)
	time_checkout = models.DateTimeField(blank=True, null=True)

	def get_attending(self, idnumber):
		print(idnumber)
		#attend = self.objects.exists(member_id = ids)
		return idnumber

	def __unicode__(self):
		return u'%s %s %s %s %s' % (self.event_role, self.member, self.attendance, self.time_checkin, self.time_checkout)

class EventCreation(ModelForm):
	class Meta:
		model = Event
		fields = '__all__'
	title = forms.CharField(max_length=64,label='Titill:',initial='Titill', widget=forms.TextInput(attrs={'placeholder': 'Titill viðburðar'}))
	date_time_begin = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Hefst:', widget=forms.TextInput(attrs={'placeholder': 'Upphaf'}))
	date_time_end   = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Lýkur:', widget=forms.TextInput(attrs={'placeholder': 'Lok'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'cols': '80', 'rows': '5'}),label='',initial='Lýsing')
	event_type = forms.ModelChoiceField(queryset=EventType.objects.all(), empty_label='(ekkert)')

class EventQuickCreation(ModelForm):
	class Meta:

groups/models.py
# -*- coding: utf-8 -*-
from django.db import models
from members.models import Member
from datetime import datetime

class Group(models.Model):
	title = models.CharField(max_length=64)
	slug = models.SlugField()
	description = models.TextField(blank=True)
	members = models.ManyToManyField(Member, through='Membership')
	GROUP_TYPE_CHOICES = (
		(u'UH', u'útkallshópur'),
		(u'AH', u'almennur hópur'),
		(u'FL', u'flokkur'),
	)
	group_type = models.CharField(max_length=2, choices=GROUP_TYPE_CHOICES, default='UH')
	#qualifications = models.ManyToManyField(Qualification, through='Qualify')
	
	def __unicode__(self):
		return self.title

class Membership(models.Model):
	member = models.ForeignKey(Member)
	group = models.ForeignKey(Group)
	date_joined = models.DateField(default=datetime.now)
	is_manager = models.BooleanField(default=False)

	def __unicode__(self):
		return self.group.title + ': ' + self.member.user.first_name + ' ' + self.member.user.last_name

#class Qualify(models.Model):
#	qualification = models.ForeignKey(Qualification)
#	group = models.ForeignKey(Group)
# TODO: Is a required minimum number really useful?
#	required_minimum_number = models.PositiveSmallIntegerField(default='0')

members/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import *
#from django.contrib.localflavor.is_.forms import ISIdNumberField, ISPhoneNumberField

class Position(models.Model):
	# Members can have various positions such as on-call, in training, etc.

	title = models.CharField(max_length=32)

	def __unicode__(self):
		return self.title

class Member(models.Model):
	# This is an object to augment the Django auth system user.
	#
	# The Member has a one-to-one relation to the User but furthermore has:
	# * a member_id which we want for the Icelandic “kennitala”
	# * a position which describes the member status (on-call, in training, etc.)
	# * an address
	# * a text field for general information
	# Furthermore, the Member object has a one-to-many relationship to:
	# * phone numbers (members.phone)
	# * email addresses (members.phone)
	# and a many-to-many relationship to
	# * Group (groups.group)

	user = models.OneToOneField(User)
	member_id = models.IntegerField()
	position = models.ForeignKey(Position, default=Position.objects.filter(id=1))
	address = models.TextField(blank=True)
	info = models.TextField(blank=True)
	
	def __unicode__(self):
		return self.user.first_name +' '+ self.user.last_name

	def name(self):
		return self.user.first_name +' '+ self.user.last_name

#	TODO: Currently we're just using the auth model email address for the
#	primary, but we might want to add a way to order (not just mark one) the
#	email addresses.
#
#	def email(self):
#		# Return the first primary email address
#		e = Email.objects.filter(member=self, is_primary=True)
#		try:
#			return e[0]
#		except:
#			return ""

#	TODO: This makes for excessive database calls. Solve some other way.
#	def phone(self):
#		# Return the first primary phone number
#		p = Phone.objects.filter(member=self, is_primary=True)
#		try:
#			return p[0]
#		except:
#			return ""

class Phone(models.Model):
	member = models.ForeignKey(Member)
	number = models.IntegerField()
	#number = models.ISPhoneNumberField()
	is_primary = models.BooleanField(default=False)
	
	def __unicode__(self):
		return str(self.number)

class Email(models.Model):
	member = models.ForeignKey(Member)
	address = models.EmailField(max_length=254)
	is_primary = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.address

templates/members/member_page.html
{% extends "tsar.html" %}
{% load staticfiles %}

{% block head %}
	<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
	<link type="text/css" rel="stylesheet" href="{% static "css/chosen.css" %}" />
<style type="text/css">
.edit-interface { display: none; }
</style>
<script type="text/javascript">
$(document).ready(function(){
	$('#missing-qualifications-list').chosen();
	$('#missing-groups-list').chosen();
});
</script>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-lg-6 col-md-7 col-sm-7">
		<section id="member-details">
			<h2>{{ member.user.first_name }} {{ member.user.last_name }}</h2>
			<div class="row">
				<div class="col-xs-6">
					<dl>
						<dt>Nafn:</dt>
						<dd>{{ member.user.first_name }} {{ member.user.last_name }}</dd>
						<dt>Kennitala:</dt>
						<dd>{{ member.member_id }}</dd>
						<dt>Símanúmer:</dt>
						{% for phone in member.phone_set.all %}
						<dd><a href="tel:{{ phone.number }}">{{ phone.number }}</a></dd>
						{% endfor %}
						<dt>Tölvupóstfang</dt>
						<dd><a href="mailto:{{ member.user.email }}">{{ member.user.email }}</a></dd>
						<dt>Heimilisfang:</dt><dd>{{ member.address }}</dd>
						<dt>Staða:</dt>
						<dd>{{ member.position }}</dd>
					</dl>
				</div>
				<div class="col-xs-6">
			<div id="profile-picture"><img src="{% static "img/hssr-merki.png" %}" alt="Member profile picture" class="img-responsive" /></div>
				</div>
			</div>
		</section>
	</div>

	<div class="col-lg-3 col-md-5 col-sm-5">
		<section id="member-groups">
			<h2>Hópar
				<input type="button" class="btn btn-default pull-right btn-sm" value="Sýsla" style="vertical-align: bottom;" onclick="$('#member-groups-edit').toggle('600');$(this).toggleClass('btn-primary btn-default');($(this).val()=='Lokið')?$(this).val('Sýsla'):$(this).val('Lokið');" />
			</h2>
			<ul>
{% for group in member.group_set.all %}
				<li><a href="/hopur/{{ group.slug }}">{{ group.title }}</a></li>
{% endfor %}
			</ul>
			<div id="member-groups-edit" class="input-append edit-interface">
				<select id="missing-groups-list" multiple data-placeholder="Nafn">
			{% for q in missing_groups_list %}
					<option>{{ q }}</option>
			{% endfor %}
				</select>
	<!--<input type="text" value="Nafn" />-->
				<input type="button" class="btn btn-default" value="Bæta við" />
			</div>
		</section>

		<section id="member-qualifications">
			<h2>Hæfni
				<input type="button" class="btn btn-default pull-right btn-sm" value="Sýsla" style="vertical-align: bottom;" onclick="$('#member-qualifications-edit').toggle('600');$(this).toggleClass('btn-primary btn-default');($(this).val()=='Lokið')?$(this).val('Sýsla'):$(this).val('Lokið');" />
			</h2>
			<ul>
				<li>Frímerkjasöfnun (rennur út <time datetime="2028-11-22">eftir 49 mánúði</time>)</li>
				<li>Réttritun (rennur út <time datetime="2028-11-22">á morgun</time>)</li>
				<li>Heilaskurðlæknignar</li>
			</ul>
			<div id="member-qualifications-edit" class="input-append edit-interface">
				<select id="missing-qualifications-list" multiple data-placeholder="Nafn">
			{% for q in missing_qualifications_list %}
					<option>{{ q }}</option>
			{% endfor %}
				</select>
	<!--<input type="text" value="Nafn" />-->
				<input type="button" class="btn btn-default" value="Bæta við" />
			</div>
		</section>
	</div>

	<div class="clearfix visible-md visible-sm visible-xs"></div>
	<div class="col-lg-3">
		<section id="member-events">
			<!-- TODO: This must be modified to list events that the member actually attended. -->
			<h2>Seinustu viðburðir</h2>
			<ul>
{% for invitation in member.memberinvitation_set.all %}
				<li><a href="/vidburdur/{{ invitation.event_role.event.id }}">{{ invitation.event_role.event.title }}</a></li>
{% endfor %}
			</ul>
		</section>
	</div>
		
</div><!-- /.row -->

<div class="row">
	<div class="col-sm-12">
		<section id="tolfraedi">
			<h2>Tölfræði</h2>
		</section>
	</div>
</div><!-- /.row -->
{% endblock %}

templates/members/members_list.html
{% extends "tsar.html" %}

{% block content %}
<section id="felagar">
<h2>Félagatal</h2>
<ul>
{% for member in member_list.all %}
	<li><a href="/felagi/{{ member.user.username }}">{{ member.user.first_name }} {{ member.user.last_name }}</a></li>
{% endfor %}
</ul>
</section>
{% endblock %}