checkin/urls.py
from django.conf.urls import patterns, include, url
from events.models import Event

urlpatterns = patterns('',
	url(r'^$', 'checkin.views.checkin'),
	url(r'^add$','checkin.views.event_checkin', name='checkin'),
	url(r'^edit/(?P<event_id>\d+)/$', 'checkin.views.edit_event'),
	url(r'^edit/checkin$','checkin.views.checkin_edit'),
)

tsar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'tsar.views.home', name='home'),
	url(r'^$', 'tsar.views.my_page', name='home'),
	url(r'^news/$', 'tsar.views.news', name='news'),

	url(r'^hopur/', include('groups.urls')),
	url(r'^felagi/', include('members.urls')),
	url(r'^vidburdur/', include('events.urls')),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
	url(r'^utskra/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/'}),
	url(r'^checkin/', include('checkin.urls')),
	url(r'^checkin/$', include('checkin.urls')),

	#urls for password reset
	url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
	url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
	url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

from django.conf import settings

if settings.DEBUG:
	urlpatterns += patterns('',
		#(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/martin/devel/tsar/static/' }),
	)

checkin/models.py
from django.db import models

# Create your models here.

events/models.py
# -*- coding: utf-8 -*-
from django.db import models
from groups.models import Group
from members.models import Member, Position
from django.db.models import get_model
import datetime
from django import forms
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import SplitDateTimeWidget
from markupfield.fields import MarkupField
#from paintstore.fields import ColorPickerField
from colorful.fields import RGBColorField

class Role(models.Model):
	# Roles for participants in an event. (e.g. driver, organiser, instructor,
	# etc.).

	title = models.CharField(max_length=64)

	def __unicode__(self):
		return self.title

class EventType(models.Model):
	# Events may be of several different types that one may like to distinguish
	# between (e.g. exercise, course, meeting, social, etc.).
	#
	# TagTypes also have EventTypes as an exercise may have different tags to a
	# meeting.

	title = models.CharField(max_length=64)
	description = models.TextField(blank=True)
	#color = ColorPickerField(default="#ffffff")
	color = RGBColorField()

	def __unicode__(self):
		return self.title

class TagType(models.Model):
	# TagTypes group tags by type such as organiser, task, conditions, equipment
	# etc.
	#
	# A TagType is associated with one or more EventTypes to which it applies.
	# Most event types will have an organiser but different event types will have
	# different tasks.

	title = models.CharField(max_length=64)
	event_type = models.ManyToManyField(EventType)

	def __unicode__(self):
		return self.title + ": " + ", ".join([et.title for et in self.event_type.all()])

class Tag(models.Model):
	# Events have Tags for analysis. These should be chosen depending on which
	# elements should be focused on in each type of event. Exercises could for
	# example be tagged with first-aid, avalanche rescue or similar techniques.
	#
	# Tags are grouped into TagTypes (e.g. organiser, task, conditions, equipment,
	# etc.).
	title = models.CharField(max_length=64)
	tag_type = models.ForeignKey(TagType)

	def __unicode__(self):
		return self.title
		  
class Event(models.Model):
	# The fundamental object. Most of the magic happens in EventRole, however.
	#
	# An event may have several roles and members can be invited to one or more
	# roles, either as members, or through groups which they belong to.
	#
	# Events come in various types, have locations and can be tagged with
	# techniques employed or something similar that will aid in analysing events.

	title = models.CharField(max_length=64)
	#description = models.TextField(blank=True)
	#description = MarkupField(blank=True,default_markup_type='markdown')
	description = MarkupField(markup_type='markdown')
	#description = MarkupField(blank=True, markup_type='markdown')
	date_time_begin = models.DateTimeField()
	date_time_end = models.DateTimeField()
	event_type = models.ForeignKey(EventType)
	tags = models.ManyToManyField(Tag, through='EventTag', related_name='tag_events', blank=True)

	def invited_roles(self, member):
		# Returns a list of roles a member is invited to.

		invitedroles = []
		#print self.eventrole_set.all()
		for eventrole in self.eventrole_set.all():
			if eventrole.is_open:
				invitedroles.append(eventrole)
			for position in eventrole.invited_positions.all():
				if member in position.member_set.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			for group in eventrole.invited_groups.all():
				if member in group.members.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			if member in eventrole.invited_members.all() and eventrole not in invitedroles:
				invitedroles.append(eventrole)
		return invitedroles

	def responded_roles(self, member):
		# Returns a list of roles a member has responded to.

		respondedroles = []
		for eventrole in self.eventrole_set.all():
			if member in eventrole.responses.all():
				respondedroles.append(eventrole)
		return respondedroles

	#def event_roles (self):
	#	eventroles = []
	#	for eventrole self.eventrole_set.all().
	#		eventroles.append(eventrole)
	#	return eventroles

	# TODO: Need to implement locations. Character fields or just store this all in a GPX file?
	# TODO: Add equipment to log equipment use. Better to add this as a relation rather than a tag?

	def __unicode__(self):
		return self.title

class EventTag(models.Model):
	event = models.ForeignKey(Event)
	tag = models.ForeignKey(Tag)

	def __unicode__(self):
		return self.event.title +' <-> '+ self.tag.title

class EventRole(models.Model):
	# An event may have several roles, and the same group or member may be
	# invited to each of these. So for each role on each event we need an
	# “event role” to which we'll hang the invitations.
	#
	# These EventRoles are associated with:
	# * an event
	# * a role
	# * (optionally) one or more groups through GroupInvitation
	# * (optionally) one or more members through MemberInvitation
	# * (optionally) one or more positions through PositionInvitation
	# * a boolean field indicating whether the event is open to all members
	# * (optionally) one or more members through their responses to the event
	# EventRoles furthermore have:
	# * an optional maximum number of members allowed
	# * an optional minimum number of members required
	# * a boolean indicating whether the role details should be hidden to non-invited members

	event = models.ForeignKey(Event)
	role = models.ForeignKey(Role)
	invited_groups = models.ManyToManyField(Group, through='GroupInvitation', blank=True)
	invited_members = models.ManyToManyField(Member, through='MemberInvitation', related_name='eventrole_invitations', blank=True)
	invited_positions = models.ManyToManyField(Position, through='PositionInvitation', blank=True)
	is_open = models.BooleanField(default=False)
	responses = models.ManyToManyField(Member, through='MemberResponse', related_name='eventrole_responses', blank=True)
	minimum = models.SmallIntegerField(default=0)
	maximum = models.SmallIntegerField(default=0)
	is_hidden = models.BooleanField(default=False)

	def invited(self, member):
		# Returns boolean depending on whether the member is invited to the event.
		# TODO: Unused?

		for position in self.invited_positions.all():
			if member in position.members.all():
				return True
		for group in self.invited_groups.all():
			if member in group.members.all():
				return True
		if member in self.invited_members.all():
			return True
		return False

	def response(self, member):
		# Returns the member's response to the event, unless there is none in
		# which case the response is the string 'U'.

		try:
			mr = MemberResponse.objects.get(event_role=self,member=member)
			#print 'XXX',mr.response
			return mr.response
		except:
			#print 'XXX NO RESPONSE'
			return 'U'

	def __unicode__(self):
		return self.event.title +' '+ self.role.title

class PositionInvitation(models.Model):
	# An intermediary model between an event role and a position.

	event_role = models.ForeignKey(EventRole)
	position = models.ForeignKey(Position)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.position.title

class GroupInvitation(models.Model):
	# An intermediary model between an event role and a group.

	event_role = models.ForeignKey(EventRole)
	group = models.ForeignKey(Group)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.group.title

class MemberInvitation(models.Model):
	# An intermediary model between an event role and a member.

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberResponse(models.Model):
	# An intermediary model between an event role and a member.
	#
	# The MemberResponse details the response (whether the member is attending or
	# will be absent) and the time of the response (important for roles which
	# have a maximum number of slots).

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_RESPONSES = (
		(u'Y',u'Attending'),
		(u'N',u'Absent'),
		(u'U',u'Unclear'),
	)
	response = models.CharField(max_length=1, choices=EVENT_RESPONSES)
	# TODO: Should we add this to help gather a bit of data on member event response behaviour or is it a bit to Big-Brothery?
	#prior = models.CharField(max_length=1, choices=EVENT_RESPONSES, blank=True)
	time_responded = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberAttendance(models.Model):
	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_ATTENDANCE = (
		(u'Y',u'Attended'),
		(u'N',u'Absent'),
	)
	attendance = models.CharField(max_length=1, choices=EVENT_ATTENDANCE)
	time_checkin = models.DateTimeField(blank=True, null=True)
	time_checkout = models.DateTimeField(blank=True, null=True)

	def get_attending(self, idnumber):
		print(idnumber)
		#attend = self.objects.exists(member_id = ids)
		return idnumber

	def __unicode__(self):
		return u'%s %s %s %s %s' % (self.event_role, self.member, self.attendance, self.time_checkin, self.time_checkout)

class EventCreation(ModelForm):
	class Meta:
		model = Event
		fields = '__all__'
	title = forms.CharField(max_length=64,label='Titill:',initial='Titill', widget=forms.TextInput(attrs={'placeholder': 'Titill viðburðar'}))
	date_time_begin = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Hefst:', widget=forms.TextInput(attrs={'placeholder': 'Upphaf'}))
	date_time_end   = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Lýkur:', widget=forms.TextInput(attrs={'placeholder': 'Lok'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'cols': '80', 'rows': '5'}),label='',initial='Lýsing')
	event_type = forms.ModelChoiceField(queryset=EventType.objects.all(), empty_label='(ekkert)')

class EventQuickCreation(ModelForm):
	class Meta:

templates/checkin/checkin_index.html
{% extends "tsar.html" %}

{% block head %}
<script type="text/javascript" src="/static/js/development-bundle/ui/jquery-ui-1.8.21.custom.js"></script>
<script type="text/javascript" src="/static/js/development-bundle/ui/minified/jquery.ui.datepicker.min.js"></script>
<script type="text/javascript" src="/static/js/development-bundle/ui/ui.datepicker-is.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui-timepicker-addon.js"></script>
<link type="text/css" rel="stylesheet" href="/static/js/css/ui-lightness/jquery-ui-1.8.21.custom.css" />
<script type="text/javascript" src="/static/js/chosen.jquery.min.js"></script>
<link type="text/css" rel="stylesheet" href="/static/css/chosen.css" />
<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
<!--<script type="text/javascript" src="/static/js/tsar.events.js"></script> -->
<style>
.label {font: normal 6px courier !important;}
.events_list { list-style: none; margin-left: 0.3em; }
.overflow { display: none; }
.h5 { color: liturinn; background-color: bakgrunnurinn; }
.fill {height: 100%;}
.container-fluid {}
	/* css for timepicker */
	//.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
	//.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
	//.ui-timepicker-div dl { text-align: left; }
	//.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
	//.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
    //.ui-timepicker-div td { font-size: 12px; }
	//.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }
.required { border-color: rgb(233, 175, 102);outline: 0px none;box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(233, 175, 102, 0.6); }
</style>
<script>

$(document).ready(function(){
	setTimeout("location.reload(true);",30000);
   	$('.respond-icon').click(function(event) { event.stopPropagation(); checkin(this, 'Checkin'); } );
   	$("[data-toggle=popover]").popover({
    html: true, 
	content: function() {
          return $('#popover-content').html();
        }

	});
	$('#id_date_time_begin').css('margin-bottom','5px');
	$('#id_date_time_begin, #id_date_time_end').css('font-size','.4em');
	$('#id_title, #id_date_time_begin, #id_date_time_end').css('height','auto');
	$('#id_date_time_begin, #id_date_time_end').css('width','auto');
	$('#id_title, #event_type, #id_date_time_begin, #id_date_time_end, #id_description').addClass('form-control');
	$('#event_header *').css('padding-right', '5px');
	$('#event_header *').css('padding-left', '5px');
	$('#add_dates_btn').parent().css('padding-right', '15px');
	$('#add_dates_btn').css('font-size','2.27em');
	$('#add_dates_btn').css('height','auto');

	$('#id_title, #id_date_time_begin, #id_date_time_end').addClass('required');
	$('#id_title, #id_date_time_begin, #id_date_time_end').live('blur', function(element) {
		console.log($(this).val());
		if ($(this).val() == "") {
			$(this).addClass('required');
		} else {
			$(this).removeClass('required');
		}
	});

	startDateTextBox = $('#id_date_time_begin')
	endDateTextBox = $('#id_date_time_end')

	$('#id_date_time_begin').datetimepicker({
		onClose: function (selectedDateTime){
			var select_dt = new Date(selectedDateTime);
			var original_end = endDateTextBox.val();
			var testEndDate = endDateTextBox.datetimepicker('getDate');
			endDateTextBox.datetimepicker('option', 'minDate', startDateTextBox.datetimepicker('getDate') );
	
  	      if (original_end != '') {
  	          if(testEndDate < select_dt){
  	              endDateTextBox.val(selectedDateTime);
  	          }else{
  	              endDateTextBox.val(original_end);
  	          }
  	      }else{
  	          endDateTextBox.val(selectedDateTime);
  	      }
		}

	});
	$('#id_date_time_end').datetimepicker({
		onClose: function (selectedDateTime){
			var select_dt = new Date(selectedDateTime);
			var original_start = startDateTextBox.val();
			var testStartDate = startDateTextBox.datetimepicker('getDate');
			startDateTextBox.datetimepicker('option', 'maxDate', endDateTextBox.datetimepicker('getDate') );

			if (original_start != '') {
				if(testStartDate > select_dt){
					startDateTextBox.val(selectedDateTime);
				}else{
					startDateTextBox.val(original_start);
				}
			}else{
				startDateTextBox.val(selectedDateTime);
			}
		}
	});

	$('.select-participants').chosen({width: "95%"});

	/*var csrftoken = $.cookie('csrftoken');
	console.log('CSRF (on page):'+csrftoken);*/

	$('#quick_save').on('submit',function(event) {
		event.preventDefault();
		var title = $("#id_title").val();
		console.log("Form submitted");
		quick_save_event();

		//var node='init';
		//json = JSON.stringify(title);
		//csrf = $.cookie('csrftoken');
		//console.log("woot1");
		//var posting = $.post("/vidburdur/nyskraning/quicksave", {'data': json});
	});
});
/*function submit_form(){

	var title = $("#id_title").val();
	console.log(title);
	var node='init';
	json = JSON.stringify(title);
	csrf = $.cookie('csrftoken');
	console.log("woot1");
	var posting = $.post("/vidburdur/nyskraning/quicksave", {'csrfmiddlewaretoken': csrf, 'data': json});

} */
function quick_save_event(){
	console.log("quicksave is working")
	console.log($('#id_title').val())
	var posting = $.post("/vidburdur/nyskraning/quicksave", {'data': $('#id_title').val()});
	//var posting = $.post("/vidburdur/nyskraning/vista", {'csrfmiddlewaretoken': csrf, 'data': json});
		/*$.ajax({
		url: "../vidburdur/nyskraning/quicksave",
		type: "POST",
		data: {the_post : $("#id_title").val() },

		success: function(json) {
			console.log(json);
			console.log("Success");
		},
		error: function (xhr,errmsg,err) {
			console.log("Error");
		}
	});*/
}

function cancel(){
}

</script>
{% endblock %}

{% block page_title %}<h1>Mæting
<style>
.form-control {width:350px;}
.popover {max-width:400px;}
</style>
    <button type="button" class="btn btn-default btn-lg" id="quickcreation" data-toggle="modal" data-target="#myModal">
  		<span class="fa fa-lg fa-list-alt" aria-hidden="true"></span> Flýtiskráning
	</button>
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  		<div class="modal-dialog">
    		<div class="modal-content">
      			<div class="modal-header">
        			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        			<h4 class="modal-title" id="myModalLabel">Flýtiskráning</h4>
      			</div>
    	  		<div class="modal-body">
    	  			<form  method="post" id="quick_save">
    	  			{% csrf_token %}
	    	  			<div class="container-fluid">
	        				<div class="row">
	        					<div class="col-md-4"><h4>Titill</h4></div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-4">{{ form.title }}</div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-4"><h4>Lýsing</h4></div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-4">{{ form.description }}</div>
	        				</div>        				
	        				<div class="row">
	        					<div class="col-md-4"><h4>Tími</h4></div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-4">{{ form.date_time_begin }}</div>
	        					<div class="col-md-4">{{ form.date_time_end }}</div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-4"><h4>Þátttakendur</h4></div>
	        				</div>
	        				<div class="row">
	        					<div class="col-md-8">
	        						<select id="id_select" name="temp" multiple data-placeholder="Veldu þáttakendur" class="select-participants">
	        							<optgroup label="Meðlimir">
	        								{% for member in members %}
												<option value="m{{ member.id }}">{{ member }}</option>
											{% endfor %}
										</optgroup>'
	        						</select>
	        					</div>
	        				</div>
	      				</div>
	      				<div class="modal-footer">
	        				<button type="button" class="btn btn-default" data-dismiss="modal" onclick="cancel()">Hætta við</button>
	        				<button type="submit" id="create-event-button" class="btn btn-primary">Vista</button>
	      				</div>
      				</form>
      			</div>
    		</div>
  		</div>
	</div>
</h1>{% endblock %}
{% block content %}
<style>
.container-fluid {}
</style>
{% load app_tags %}

<div class="container-fluid fill">
	<div class="row" id="1">
	{% for event in events_list %}
		{% if forloop.counter < 9 %}	
			<div class="col-lg-3 col-md-6">
				<section id="vidburdir">
				<h2 class="list-group-item-heading" style="display:inline;">{{event.title}}</h2>
				<a href="/checkin/edit/{{ event.id }}">
				<span id="edit_{{event.id}}"  data-eventid="{{event.id}}"  data-action="edit" class="edit-icon fa fa-lg fa-edit" style="text-align:right;"></span>
				</a>
				<ul id="checkin" class="events_list list-unstyled">
				{% for event_role in event.eventrole_set.all %}		
					<div style="border-bottom: 1px solid #eee;">{{event_role.role.title}}<br></div>
						<ul class="events_list list-unstyled">
						{% for member_response in event_role.memberresponse_set.all %}
						{% for member_attendance in member_response_attendance%}
						{% if member_response.event_role_id == member_attendance.event_role_id and member_response.member_id == member_attendance.member_id%}
						{% if member_response.response == 'Y' %}
            			<li id="event_attend-{{event.id}}_{{ member_response.member.id }}_tooltip"data-toggle="tooltip" data-placement="right" title="INN: {{member_attendance.time_checkin|time:'H:i:s'}} &#013; ÚT: {{member_attendance.time_checkout|time:'H:i:s'}}">
            				{% if member_attendance.attendance %}
            					{% if member_attendance.attendance and member_attendance.time_checkout != null %}
            					<span id="event_attend-{{event.id}}_{{ member_response.member.id }}_status_icon" class="fa fa-lg fa-check-square status-icon " style="color:red"></span>
            					{% elif member_attendance.time_checkout == null %}
            					<span id="event_attend-{{event.id}}_{{ member_response.member.id }}_status_icon" class="fa fa-lg fa-check-square status-icon " style="color:green"></span>
            					{% endif %}
            				{% else %}
            				<span id="event_attend-{{event.id}}_{{ member_response.member.id }}_status_icon" class="fa fa-lg fa-check-square status-icon "></span>
            				{% endif %}
            			{{ member_response.member }}
            			<span class="response-icons">
            				{% if member_attendance.attendance and member_attendance.time_checkout == null %}
            					<span id="attend-{{event.id}}_{{ member_response.member.id }}" data-member="{{ member_response.member.id }}" data-eventid="{{event.id}}" data-roleid="{{event_role.role.id}}" data-action="checkout" data-eventroleid="{{event_role.id}}" class="respond-icon fa fa-lg fa-sign-out" ></span>
							{% elif member_attendance.attendance and member_attendance.time_checkout != null%}
							
							{% else %}
							<span id="attend-{{event.id}}_{{ member_response.member.id }}" data-member="{{ member_response.member.id }}" data-eventid="{{event.id}}" data-roleid="{{event_role.role.id}}" data-action="attend" data-eventroleid="{{event_role.id}}" class="respond-icon fa fa-lg fa-sign-in"></span>
							{% endif %}
						</span>

						</li>{% endif %}
						{% endif %}
						{% endfor %}
						{% endfor %}
               			</ul>
				{% endfor %}
				</ul>
				</section>
			</div>		
		{% endif %}
	{% endfor %}
</div>
</div>
{% endblock %}