events/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView
from events.models import Event

urlpatterns = patterns('events.views',
	url(r'^$', 'list_events', name='events'),
	#url(r'^(?P<pk>\d+)/$',
	#	DetailView.as_view(
	#		model=Event,template_name='events/event_page.html')
	#	),
	url(r'^(?P<pk>\d+)/$','display_event', name='events'),
	url(r'^(?P<pk>\d+)/svara$','event_response', name='events'),
	url(r'^svara$','event_response', name='events'),
	#url(r'^(?P<pk>\d+)/breyta',
	#	DetailView.as_view(
	#		model=Event,template_name='events/create_event.html')
	#	),
	url(r'^nyskraning/$', 'display_event_form', name='events'),
	url(r'^nyskraning/vista$', 'save_event', name='events'),
	url(r'^nyskraning/quicksave$', 'quick_save', name='events'),
)

tsar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'tsar.views.home', name='home'),
	url(r'^$', 'tsar.views.my_page', name='home'),
	url(r'^news/$', 'tsar.views.news', name='news'),

	url(r'^hopur/', include('groups.urls')),
	url(r'^felagi/', include('members.urls')),
	url(r'^vidburdur/', include('events.urls')),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
	url(r'^utskra/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/'}),
	url(r'^checkin/', include('checkin.urls')),
	url(r'^checkin/$', include('checkin.urls')),

	#urls for password reset
	url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
	url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
	url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),

	# Uncomment the admin/doc line below to enable admin documentation:
	# url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

from django.conf import settings

if settings.DEBUG:
	urlpatterns += patterns('',
		#(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/martin/devel/tsar/static/' }),
	)

events/models.py
# -*- coding: utf-8 -*-
from django.db import models
from groups.models import Group
from members.models import Member, Position
from django.db.models import get_model
import datetime
from django import forms
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import SplitDateTimeWidget
from markupfield.fields import MarkupField
#from paintstore.fields import ColorPickerField
from colorful.fields import RGBColorField

class Role(models.Model):
	# Roles for participants in an event. (e.g. driver, organiser, instructor,
	# etc.).

	title = models.CharField(max_length=64)

	def __unicode__(self):
		return self.title

class EventType(models.Model):
	# Events may be of several different types that one may like to distinguish
	# between (e.g. exercise, course, meeting, social, etc.).
	#
	# TagTypes also have EventTypes as an exercise may have different tags to a
	# meeting.

	title = models.CharField(max_length=64)
	description = models.TextField(blank=True)
	#color = ColorPickerField(default="#ffffff")
	color = RGBColorField()

	def __unicode__(self):
		return self.title

class TagType(models.Model):
	# TagTypes group tags by type such as organiser, task, conditions, equipment
	# etc.
	#
	# A TagType is associated with one or more EventTypes to which it applies.
	# Most event types will have an organiser but different event types will have
	# different tasks.

	title = models.CharField(max_length=64)
	event_type = models.ManyToManyField(EventType)

	def __unicode__(self):
		return self.title + ": " + ", ".join([et.title for et in self.event_type.all()])

class Tag(models.Model):
	# Events have Tags for analysis. These should be chosen depending on which
	# elements should be focused on in each type of event. Exercises could for
	# example be tagged with first-aid, avalanche rescue or similar techniques.
	#
	# Tags are grouped into TagTypes (e.g. organiser, task, conditions, equipment,
	# etc.).
	title = models.CharField(max_length=64)
	tag_type = models.ForeignKey(TagType)

	def __unicode__(self):
		return self.title
		  
class Event(models.Model):
	# The fundamental object. Most of the magic happens in EventRole, however.
	#
	# An event may have several roles and members can be invited to one or more
	# roles, either as members, or through groups which they belong to.
	#
	# Events come in various types, have locations and can be tagged with
	# techniques employed or something similar that will aid in analysing events.

	title = models.CharField(max_length=64)
	#description = models.TextField(blank=True)
	#description = MarkupField(blank=True,default_markup_type='markdown')
	description = MarkupField(markup_type='markdown')
	#description = MarkupField(blank=True, markup_type='markdown')
	date_time_begin = models.DateTimeField()
	date_time_end = models.DateTimeField()
	event_type = models.ForeignKey(EventType)
	tags = models.ManyToManyField(Tag, through='EventTag', related_name='tag_events', blank=True)

	def invited_roles(self, member):
		# Returns a list of roles a member is invited to.

		invitedroles = []
		#print self.eventrole_set.all()
		for eventrole in self.eventrole_set.all():
			if eventrole.is_open:
				invitedroles.append(eventrole)
			for position in eventrole.invited_positions.all():
				if member in position.member_set.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			for group in eventrole.invited_groups.all():
				if member in group.members.all() and eventrole not in invitedroles:
					invitedroles.append(eventrole)
			if member in eventrole.invited_members.all() and eventrole not in invitedroles:
				invitedroles.append(eventrole)
		return invitedroles

	def responded_roles(self, member):
		# Returns a list of roles a member has responded to.

		respondedroles = []
		for eventrole in self.eventrole_set.all():
			if member in eventrole.responses.all():
				respondedroles.append(eventrole)
		return respondedroles

	#def event_roles (self):
	#	eventroles = []
	#	for eventrole self.eventrole_set.all().
	#		eventroles.append(eventrole)
	#	return eventroles

	# TODO: Need to implement locations. Character fields or just store this all in a GPX file?
	# TODO: Add equipment to log equipment use. Better to add this as a relation rather than a tag?

	def __unicode__(self):
		return self.title

class EventTag(models.Model):
	event = models.ForeignKey(Event)
	tag = models.ForeignKey(Tag)

	def __unicode__(self):
		return self.event.title +' <-> '+ self.tag.title

class EventRole(models.Model):
	# An event may have several roles, and the same group or member may be
	# invited to each of these. So for each role on each event we need an
	# “event role” to which we'll hang the invitations.
	#
	# These EventRoles are associated with:
	# * an event
	# * a role
	# * (optionally) one or more groups through GroupInvitation
	# * (optionally) one or more members through MemberInvitation
	# * (optionally) one or more positions through PositionInvitation
	# * a boolean field indicating whether the event is open to all members
	# * (optionally) one or more members through their responses to the event
	# EventRoles furthermore have:
	# * an optional maximum number of members allowed
	# * an optional minimum number of members required
	# * a boolean indicating whether the role details should be hidden to non-invited members

	event = models.ForeignKey(Event)
	role = models.ForeignKey(Role)
	invited_groups = models.ManyToManyField(Group, through='GroupInvitation', blank=True)
	invited_members = models.ManyToManyField(Member, through='MemberInvitation', related_name='eventrole_invitations', blank=True)
	invited_positions = models.ManyToManyField(Position, through='PositionInvitation', blank=True)
	is_open = models.BooleanField(default=False)
	responses = models.ManyToManyField(Member, through='MemberResponse', related_name='eventrole_responses', blank=True)
	minimum = models.SmallIntegerField(default=0)
	maximum = models.SmallIntegerField(default=0)
	is_hidden = models.BooleanField(default=False)

	def invited(self, member):
		# Returns boolean depending on whether the member is invited to the event.
		# TODO: Unused?

		for position in self.invited_positions.all():
			if member in position.members.all():
				return True
		for group in self.invited_groups.all():
			if member in group.members.all():
				return True
		if member in self.invited_members.all():
			return True
		return False

	def response(self, member):
		# Returns the member's response to the event, unless there is none in
		# which case the response is the string 'U'.

		try:
			mr = MemberResponse.objects.get(event_role=self,member=member)
			#print 'XXX',mr.response
			return mr.response
		except:
			#print 'XXX NO RESPONSE'
			return 'U'

	def __unicode__(self):
		return self.event.title +' '+ self.role.title

class PositionInvitation(models.Model):
	# An intermediary model between an event role and a position.

	event_role = models.ForeignKey(EventRole)
	position = models.ForeignKey(Position)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.position.title

class GroupInvitation(models.Model):
	# An intermediary model between an event role and a group.

	event_role = models.ForeignKey(EventRole)
	group = models.ForeignKey(Group)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.group.title

class MemberInvitation(models.Model):
	# An intermediary model between an event role and a member.

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberResponse(models.Model):
	# An intermediary model between an event role and a member.
	#
	# The MemberResponse details the response (whether the member is attending or
	# will be absent) and the time of the response (important for roles which
	# have a maximum number of slots).

	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_RESPONSES = (
		(u'Y',u'Attending'),
		(u'N',u'Absent'),
		(u'U',u'Unclear'),
	)
	response = models.CharField(max_length=1, choices=EVENT_RESPONSES)
	# TODO: Should we add this to help gather a bit of data on member event response behaviour or is it a bit to Big-Brothery?
	#prior = models.CharField(max_length=1, choices=EVENT_RESPONSES, blank=True)
	time_responded = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.event_role.__unicode__() +'>'+ self.member.user.username

class MemberAttendance(models.Model):
	event_role = models.ForeignKey(EventRole)
	member = models.ForeignKey(Member)
	EVENT_ATTENDANCE = (
		(u'Y',u'Attended'),
		(u'N',u'Absent'),
	)
	attendance = models.CharField(max_length=1, choices=EVENT_ATTENDANCE)
	time_checkin = models.DateTimeField(blank=True, null=True)
	time_checkout = models.DateTimeField(blank=True, null=True)

	def get_attending(self, idnumber):
		print(idnumber)
		#attend = self.objects.exists(member_id = ids)
		return idnumber

	def __unicode__(self):
		return u'%s %s %s %s %s' % (self.event_role, self.member, self.attendance, self.time_checkin, self.time_checkout)

class EventCreation(ModelForm):
	class Meta:
		model = Event
		fields = '__all__'
	title = forms.CharField(max_length=64,label='Titill:',initial='Titill', widget=forms.TextInput(attrs={'placeholder': 'Titill viðburðar'}))
	date_time_begin = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Hefst:', widget=forms.TextInput(attrs={'placeholder': 'Upphaf'}))
	date_time_end   = forms.DateTimeField(input_formats={'%m/%d/%Y %H:%M'},label='Lýkur:', widget=forms.TextInput(attrs={'placeholder': 'Lok'}))
	description = forms.CharField(widget=forms.Textarea(attrs={'cols': '80', 'rows': '5'}),label='',initial='Lýsing')
	event_type = forms.ModelChoiceField(queryset=EventType.objects.all(), empty_label='(ekkert)')

class EventQuickCreation(ModelForm):
	class Meta:

templates/events/create_event.html
{% extends "tsar.html" %}
{% load staticfiles %}

{% block head %}
<script type="text/javascript" src="{% static "js/development-bundle/ui/jquery-ui-1.8.21.custom.js" %}"></script>
<script type="text/javascript" src="{% static "js/development-bundle/ui/minified/jquery.ui.datepicker.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/development-bundle/ui/ui.datepicker-is.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script>
<link type="text/css" rel="stylesheet" href="{% static "js/css/ui-lightness/jquery-ui-1.8.21.custom.css" %}" />
<script type="text/javascript" src="{% static "js/chosen.jquery.min.js" %}"></script>
<link type="text/css" rel="stylesheet" href="{% static "css/chosen.css" %}" />
<script type="text/javascript" src="{% static "js/jquery.cookie.js" %}"></script>
<script type="text/javascript" src="{% static "js/tsar.events.js" %}"></script>
<style>
	/* css for timepicker */
	//.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
	//.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
	//.ui-timepicker-div dl { text-align: left; }
	//.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
	//.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
	//.ui-timepicker-div td { font-size: 90%; }
	//.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }
</style>
<style>
	section { overflow: auto; }
	.select-participants, [id*='role-groups-id_'] { width: 100%; }
	div[id*='tag_type_id'] { width: 100% !important; }
	#tag_organiser_chzn, #tag_event_task_chzn, #tag_location_chzn, #tag_equipment_chzn { width: 100% !important; }
	//#id_minimum, #id_maximum { width: 2em; }
	th, td { height: 1em; }
	#role_groups_id_template_chzn, .chzn-drop, #role_groups_id_template_chzn ul li input { width: 100% !important; }

/*	#id_date_time_begin-label, #id_date_time_end-label { text-align: right; }*/
/*	#id_date_time_begin, #id_date_time_end { display: inline; width: 8em; }*/
	#id_title, #event_type, #id_date_time_begin, #id_date_time_end { width: 100% !important; }
	
	.required { border-color: rgb(233, 175, 102);outline: 0px none;box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(233, 175, 102, 0.6); }

</style>
<script type="text/javascript">

$(document).ready(function(){
	$('#id_title').css('font-size','2.57em');
	$('#id_date_time_begin').css('margin-bottom','5px');
	$('#id_date_time_begin, #id_date_time_end').css('font-size','.7em');
	$('#id_title, #id_date_time_begin, #id_date_time_end').css('height','auto');
	$('#id_title, #event_type, #id_date_time_begin, #id_date_time_end, #id_description').addClass('form-control');
	$('#event_header *').css('padding-right', '5px');
	$('#event_header *').css('padding-left', '5px');
	$('#id_title').parent().css('padding-left', '15px');
	$('#add_dates_btn').parent().css('padding-right', '15px');
	$('#add_dates_btn').css('font-size','2.27em');
	$('#add_dates_btn').css('height','auto');

	$('#id_title, #id_date_time_begin, #id_date_time_end').addClass('required');
	$('#id_title, #id_date_time_begin, #id_date_time_end').live('blur', function(element) {
		console.log($(this).val());
		if ($(this).val() == "") {
			$(this).addClass('required');
		} else {
			$(this).removeClass('required');
		}
	});

// Datetimepicker
	startDateTextBox = $('#id_date_time_begin')
	endDateTextBox = $('#id_date_time_end')
	$('#id_date_time_begin').datetimepicker({
		onClose: function (selectedDateTime){
			var select_dt = new Date(selectedDateTime);
			var original_end = endDateTextBox.val();
			var testEndDate = endDateTextBox.datetimepicker('getDate');
			endDateTextBox.datetimepicker('option', 'minDate', startDateTextBox.datetimepicker('getDate') );
	
  	      if (original_end != '') {
  	          if(testEndDate < select_dt){
  	              endDateTextBox.val(selectedDateTime);
  	          }else{
  	              endDateTextBox.val(original_end);
  	          }
  	      }else{
  	          endDateTextBox.val(selectedDateTime);
  	      }
		}

	});
	$('#id_date_time_end').datetimepicker({
		onClose: function (selectedDateTime){
			var select_dt = new Date(selectedDateTime);
			var original_start = startDateTextBox.val();
			var testStartDate = startDateTextBox.datetimepicker('getDate');
			startDateTextBox.datetimepicker('option', 'maxDate', endDateTextBox.datetimepicker('getDate') );

			if (original_start != '') {
				if(testStartDate > select_dt){
					startDateTextBox.val(selectedDateTime);
				}else{
					startDateTextBox.val(original_start);
				}
			}else{
				startDateTextBox.val(selectedDateTime);
			}
		}
	});

// Chosen UI
	$('.tag-type').chosen();

	$('#id_description').addClass('col-xs-12');

// Place the CSRF token in a js variable so that the form handler can send it to the view.
	//csrf = "{{ csrf_token|escapejs }}";
	var csrftoken = $.cookie('csrftoken');
	console.log('CSRF (on page):'+csrftoken);

	// Populate with a default role
	$('#6').click();

}); //END READY -----------------------

	$('.role-dropdown-item').live('click',(function(){
		role_id = $(this).attr('id');
		role_title = $(this).children('a').html();
		$(this).remove();
	node=	'<div class="role_entry">'
		+			'<div class="role_entry-title" style="float:left">'+role_title+'</div>'
		+			'<input type="hidden" name="role['+role_id+'][id]" value="'+role_id+'" />'
		+					'<div style="float:right"><i id="'+role_id+'" class="delete-role-entry fa fa-times-circle pull-right" style="cursor: pointer"></i></div>'
//		+					'<div style="float:right; margin-right: .5em;">mest:   <input name="role['+role_id+'][max]" class="col-sm-6 role-max" type="number" min="0" value="0" max="999" style="width:2em"/></div>'
//		+					'<div style="float:right; margin-right: .5em;">minnst: <input name="role['+role_id+'][min]" class="col-sm-6 role-min" type="number" min="0" value="0" max="999" style="width:2em"/></div>'
//		+					'<div>'
//		+						'<input name="role['+role_id+'][closed]" class="btn btn-danger col-sm-12" type="button" value="lokað" onclick="$(this).toggleClass(\'btn-danger btn-success\');($(this).val()==\'lokað\')?$(this).val(\'opið\'):$(this).val(\'lokað\');" />'
//		+					'</div>'
		+		'<div>'
		+			'<select name="role['+role_id+'][participants][]" multiple data-placeholder="Veldu þáttakendur" class="select-participants">'
		+				'<optgroup label="Stöður">'
		+					'<option value="a">Allir</option>'
		+					'{% for position in positions %}'
		+					'<option value="p{{ position.id }}">{{ position.title }}</option>'
		+					'{% endfor %}'
		+				'</optgroup>'
		+				'<optgroup label="Hópar og flokkar">'
		+					'{% for group in groups %}'
		+					'<option value="g{{ group.id }}">{{ group.title }}</option>'
		+					'{% endfor %}'
		+				'</optgroup>'
		+				'<optgroup label="Meðlimir">'
		+					'{% for member in members %}'
		+					'<option value="m{{ member.id }}">{{ member }}</option>'
		+					'{% endfor %}'
		+				'</optgroup>'
		+			'</select>'
		+		'</div>'
		+	'</div>'
		+'</div>'; 
		$('#invite-role-list').append(node).children(':last').hide().fadeIn({ duration: 400, queue: false });
		// Causes a jump at the end of the slide:
		//$('#invite-role-list').append(node).children(':last').stop(true, true).hide().slideDown(500).fadeIn({ duration: 400, queue: false });
		$('.select-participants').chosen();
	}));

</script>
{% endblock %}

{% block page_title %}{% endblock %}

{% block content %}
<form id="event-creator" action="." method="post">{% csrf_token %}

	<input type="hidden" name="event_id" id="event_id" value="{{ event.pk }}" />
	
	<div id="event_header" class="row" style="margin-bottom: 1.5em;">
		<div class="col-xs-12 col-sm-7">{{ form.title }}</div>
		<div class="col-xs-5 col-sm-2">
			<select id="event_type" name="event_type" class="form-control">
						{% for type in event_types %}
				<option value="{{ type.pk }}">{{ type.title }}</option>
						{% endfor %}
			</select>
		</div>
		<div class="col-xs-3 col-sm-2">{{ form.date_time_begin }}{{ form.date_time_end }}</div>
		<div class="col-xs-1 col-sm-1"><button type="button" class="btn btn-default form-control" id="add_dates_btn" onclick="$('#add_days').slideToggle();$('#add_days_icon').toggleClass('fa-minus');"><i id="add_days_icon" class="fa fa-plus"></i></a></div>
	</div>
	
	<div id="add_days" class="tabbable" style="display:none;">
		<ul class="nav nav-tabs" style="margin-right: 0;">
			<li class="active"><a href="#reps" data-toggle="tab">Endurtaka</a></li>
			<li><a href="#days" data-toggle="tab">Bæta við</a></li>
		</ul>
		<div class="tab-content" style="border: thin solid #ddd; padding: .4em; margin-bottom: .5em; border-left: none; border-bottom: none;">
			<input class="btn btn-default" type="button" value="Sýna lista" style="float:right" onclick="$('#add_days_list').slideToggle();" />
			<div class="tab-pane" id="days">
				add days
			</div>
			<div class="tab-pane active" id="reps">
				á sama vikudegi
				<select id="reps-period" style="vertical-align: baseline; width: auto;">
					<option>í hverri viku</option>
					<option>í fyrstu og þriðju viku hvers mánaðar</option>
					<option>í annari og fjórðu viku hvers mánaðar</option>
					<option>í hverjum mánuði</option>
				</select>
				þar til <input type="text" style="width: 7em; vertical-align: baseline;" />
			</div>
			<ul id="add_days_list" style="display: none; -moz-column-count:3; /* Firefox */ -webkit-column-count:3; /* Safari and Chrome */ column-count:3;">
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
				<li><date>Ðis is a deit</date></li>
			</ul>
		</div>
	</div>


{% if error_message %}<div id="error_message">{{ error_message }}</div>{% endif %}
<div class="row">
	<div class="col-xs-12 col-sm-6 col-md-4" style="height: 100%;">
	<!-- BOÐUN Í HLUTVERK -->
		<section class="" style="overflow: visible;">
			<div class="btn-group pull-right" id="event-invite-button">
				<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Bæta við hlutverki <span class="caret"></span> </button>
				<ul id="role-dropdown" class="dropdown-menu">
	{% for role in event_roles %}
					<li class="role-dropdown-item" id="{{ role.id}}"><a>{{ role.title }}</a></li>
	{% endfor %}
				</ul>
			</div><!-- /#event-invite-button -->
		
			<h2 id="event-invite-header">Boðun</h2>
		
			<div id="invite-role-list">
			</div><!--invite-role-list-->
		</section>
	</div>

	<div class="col-xs-12 col-sm-6 col-md-8"><!-- Contains the next three sections: #description, #tags, #location -->
		<section id="description" tyle="overflow: visible">
			<h2 id="event-description-header">Lýsing</h2>
				{{ form.description }}
		</section><!-- /#description -->
	
	<!-- TAGS -->
		<section id="tags" style="overflow: visible">
			<input id="event-tag-button" type="button" class="btn btn-default" style="float: right" value="Merkja" data-toggle="button" onclick="$(this).toggleClass('active');$('#merki-content').slideToggle();" />
			<h2 id="event-tag-header">Merki</h2>
			<div id="merki-content" style="display:none">
				<table style="width: 100%">
						  {# Create a form for each TagType and mark it with the EventTypes it goes with. Then when the EventType is changed, we have to change the visibility of TagTypes that don't belong to both the new and old EventType #}
						  {% for tagtype in tagtypes %}
						  <tr>
								<td>{{ tagtype.title }}</td>
								<td>
										  <select id="tag_type_id-{{ tagtype.id }}" class="tag-type" multiple data-placeholder="Merktu umsjónaraðila">
								{% for tag in tagtype.tag_set.all %}
										  <option>{{ tag.title }}</option>
								{% endfor %}
								</select>
						  </tr>
						  {% endfor %}
				</table>
			</div>
		</section>

	<!-- LANDFRÆÐILEGAR UPPLÝSINGAR -->
		<section id="location">
			<div style="float:right; vertical-align: bottom;">
				<input id="event-geo-button" type="button" class="btn btn-default" data-toggle="button" onclick="$(this).toggleClass('active');$('#stadsetning-content').slideToggle();" value="Staðsetja" />
			</div>
			<h2 id="event-geo-header">Staðsetning</h2>
			<div id="stadsetning-content" style="display:none">
		
				<div style="float:right;"><img src="{% static "img/hengill-husmuli.png" %}" width="200" height="200" alt="Kort af svæðinu." /></div>
				<table>
					<tr><th>Lengd</th><th>Breidd</th><th colspan="2">Lýsing</th></tr>
	<!--
					<tr><td>N 64°34,392'</td><td>V 21°39,291'</td><td colspan="2">Upphafsstaður æfingar.</td></tr>
					<tr><td>N 65°01,039'</td><td>V 21°33,029'</td><td colspan="2">Söfnunarsvæði slasaðra.</td></tr>
	-->
					<tr>
						<td><input type="text" placeholder="lengd" style="width: 6em" /></td>
						<td><input type="text" placeholder="breidd" style="width: 6em" /></td>
						<td><input type="text" style="width:100%" placeholder="Lýsing" /></td>
						<td><input type="button" class="btn btn-default" value="Bæta við" style="margin-bottom:10px; margin-left: 10px;"/></td>
					</tr>
					<tr>
						<td colspan="3"><input type="text" placeholder="GPX/KML-skrá" style="min-width:30em" /></td><td><input type="button" class="btn btn-default" value="Hlaða upp" style="margin-bottom: 10px;"/></span></td>
					</tr>
				</table>
			</div>
		</section>
	</div><!-- /.col-sm-8 -->
	
</div><!-- /.row -->
	
<div class="row">
	<div class="col-sm-12">
		<section id="create-event">
			<div class="alert" style="float: left; padding-top: 4px; padding-bottom: 4px; margin-bottom: 0px; display:none" id="results"></div>
			<!--<input id="create-event-button" type="button" class="btn btn-primary pull-right" value="Vista viðburð" />-->
			<button id="create-event-button" class="btn btn-primary pull-right">Vista viðburð</button>
		</section>
	</div>
</div>

</form>

{% endblock %}